# Generated by Django 4.0.6 on 2022-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_since',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
